title: My Jekyll Site
description: A simple Jekyll site with an about page and a blog.
url: http://example.com
author:
  name: Your Name
  email: your.email@example.com
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag