title: My Jekyll Site
description: A simple Jekyll site with an about page and a blog.
url: http://vinodkhare.github.io
author:
  name: Vinod Khare
  email: vinod.khare@icloud.com
theme: cotes2020/jekyll-theme-chirpy
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# navigation links
nav_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"